Repository microsoft/cobalt, pull requests merged in 2019-06, with the labels that each got.

#160 azure simple fails due to missing app insights values
  infra/modules/providers/azure/app-insights/variables.tf
  infra/templates/azure-simple/appdev.tf
  infra/templates/azure-simple/variables.tf
Labels: bug, effort - small, pri-High

#157 Fix issue where terraform destroy is not called if terraform apply fails
  test-harness/infratests/integration.go
Labels: bug, effort - small, pri-High

#181 Sets defaults for service principle module back to original
  infra/modules/providers/azure/service-principal/main.tf
  infra/modules/providers/azure/service-principal/variables.tf
Labels: bug

#185 Service Principal Default Name Bug
  infra/modules/providers/azure/service-principal/variables.tf
Labels: bug

#184 App Service Environment template design
  infra/templates/az-isolated-service-single-region/docs/.design_images/deployment_topology.png
  infra/templates/az-isolated-service-single-region/docs/.design_images/template_topology.png
  infra/templates/az-isolated-service-single-region/docs/design.md
  test-harness/init.sh
Labels: documentation

#186 App Service End-User AuthN Design
  design-reference/architecture/authn/providers/azuread/easyauth.md
Labels: wip
