Repository microsoft/cobalt, pull requests merged in 2019-05, with the labels that each got.

#83 Fixed some typos in README and clarified some sentences as well.
  README.md
Labels: documentation

#101 Azure Simple Baseline Template
  infra/modules/providers/azure/api-mgmt/main.tf
  infra/modules/providers/azure/api-mgmt/output.tf
  infra/modules/providers/azure/api-mgmt/variables.tf
  infra/modules/providers/azure/app-gateway/main.tf
  infra/modules/providers/azure/app-gateway/variables.tf
  infra/modules/providers/azure/app-insights/README.md
  infra/modules/providers/azure/app-insights/main.tf
  infra/modules/providers/azure/app-insights/output.tf
  infra/modules/providers/azure/app-insights/variables.tf
  infra/modules/providers/azure/app-service/README.md
  infra/modules/providers/azure/app-service/azuredeploy.json
  infra/modules/providers/azure/app-service/main.tf
  infra/modules/providers/azure/app-service/output.tf
  infra/modules/providers/azure/app-service/variables.tf
  infra/modules/providers/azure/provider/main.tf
  infra/modules/providers/azure/service-plan/main.tf
  infra/modules/providers/azure/service-plan/output.tf
  infra/modules/providers/azure/service-plan/variables.tf
  infra/modules/providers/azure/tm-endpoint-ip/main.tf
  infra/modules/providers/azure/tm-endpoint-ip/output.tf
  infra/modules/providers/azure/tm-endpoint-ip/variables.tf
  infra/modules/providers/azure/tm-profile/main.tf
  infra/modules/providers/azure/tm-profile/output.tf
  infra/modules/providers/azure/tm-profile/variables.tf
  infra/modules/providers/azure/traffic-manager/main.tf
  infra/modules/providers/azure/traffic-manager/output.tf
  infra/modules/providers/azure/traffic-manager/variables.tf
  infra/modules/providers/azure/vnet/main.tf
  infra/modules/providers/azure/vnet/output.tf
  infra/modules/providers/azure/vnet/variables.tf
  infra/modules/providers/common/README.md
  infra/templates/azure-simple/README.md
  infra/templates/azure-simple/backend.tf
  infra/templates/azure-simple/main.tf
  infra/templates/azure-simple/network.tf
  infra/templates/azure-simple/terraform.tfvars
  infra/templates/azure-simple/variables.tf
Labels: effort - large

#105 This change aims to make the test harness more generic and enforces stronger linting rules during test runs.
  README.md
  devops/providers/azure-devops/templates/azure-pipelines.yml
  infra/modules/providers/azure/api-mgmt/main.tf
  infra/modules/providers/azure/api-mgmt/output.tf
  infra/modules/providers/azure/api-mgmt/variables.tf
  infra/modules/providers/azure/app-gateway/main.tf
  infra/modules/providers/azure/app-gateway/variables.tf
  infra/modules/providers/azure/app-service/main.tf
  infra/modules/providers/azure/app-service/variables.tf
  infra/modules/providers/azure/service-plan/main.tf
  infra/modules/providers/azure/service-plan/output.tf
  infra/templates/azure-simple-hw/test/integration/azure_simple_test.go
  infra/templates/azure-simple-hw/test/unit/azure_simple_test.go
  infra/templates/azure-simple/main.tf
  infra/templates/azure-simple/network.tf
  magefile.go
  test-harness/Dockerfile
  test-harness/README.md
  test-harness/docker/base-images/Dockerfile
  test-harness/infratests/infratests.go
Labels: effort - medium

#111 Adds documentation website wireframes to design-reference folder
  design-reference/docs/wireframes/choose-a-solution.png
  design-reference/docs/wireframes/guide.png
  design-reference/docs/wireframes/landing-page.png
  design-reference/docs/wireframes/pattern.png
Labels: documentation

#127 Enforce LF line endings
  .gitattributes
Labels: effort - small

#136 Azure simple template updates to support SSL termination and app service auto scale
  .env.template
  infra/modules/providers/azure/app-gateway/README.md
  infra/modules/providers/azure/app-gateway/main.tf
  infra/modules/providers/azure/app-gateway/output.tf
  infra/modules/providers/azure/app-gateway/variables.tf
  infra/modules/providers/azure/app-service/main.tf
  infra/modules/providers/azure/app-service/output.tf
  infra/modules/providers/azure/app-service/variables.tf
  infra/modules/providers/azure/keyvault-cert/README.md
  infra/modules/providers/azure/keyvault-cert/main.tf
  infra/modules/providers/azure/keyvault-cert/output.tf
  infra/modules/providers/azure/keyvault-cert/variables.tf
  infra/modules/providers/azure/keyvault-policy/README.md
  infra/modules/providers/azure/keyvault-policy/main.tf
  infra/modules/providers/azure/keyvault-policy/variables.tf
  infra/modules/providers/azure/keyvault/README.md
  infra/modules/providers/azure/keyvault/main.tf
  infra/modules/providers/azure/keyvault/output.tf
  infra/modules/providers/azure/keyvault/variables.tf
  infra/modules/providers/azure/service-plan/main.tf
  infra/modules/providers/azure/service-plan/variables.tf
  infra/modules/providers/azure/traffic-manager/README.md
  infra/modules/providers/azure/traffic-manager/output.tf
  infra/modules/providers/azure/traffic-manager/variables.tf
  infra/templates/azure-simple/README.md
  infra/templates/azure-simple/admin.tf
  infra/templates/azure-simple/appdev.tf
  infra/templates/azure-simple/backend.tf
  infra/templates/azure-simple/network.tf
  infra/templates/azure-simple/outputs.tf
  infra/templates/azure-simple/terraform.tfvars
  infra/templates/azure-simple/variables.tf
Labels: enhancement
