Repository microsoft/cobalt, pull requests merged in 2019-09, with the labels that each got.

#262 Removes extra character from image tag var in ISO template
  go.mod
  go.sum
  infra/templates/az-isolated-service-single-region/ase.tf
  infra/templates/az-isolated-service-single-region/tests/integration/integration_test.go
Labels: bug

#260 Adds a design document for the version and go process
  design-reference/architecture/VersionAndGo/readme.md
Labels: Technical Design

#261 Updates setup adpat owner doc with cli cmds
  docs/GETTING_STARTED_ADD_PAT_OWNER.md
Labels: bug, documentation

#271 Add a manual testing plan for surfacing Cobalt deployment issues
  docs/MANUAL_TESTING_PLAN.md
  test-harness/README.md
Labels: wip
